### ISSUE TITLE
[ply] Latest ply breaks slimit

### ISSUE THREAD

**Issue by brianmay** [Karaage-Cluster/karaage#264]
Reported against slimit, see https://github.com/rspivak/slimit/issues/76
Reported against ply, see https://github.com/dabeaz/ply/issues/63

**Comment by brianmay** [comment]
For reference, error is:

```
Copying '/var/cache/jenkins/tmp.cbQN2nmOVd/python2/local/lib/python2.7/site-packages/django_tables2/static/django_tables2/themes/paleblue/img/true.gif'
Post-processed 'min.css' as 'min.css'
Traceback (most recent call last):
  File "./manage.py", line 24, in <module>
    management.execute_from_command_line()
  File "/var/cache/jenkins/tmp.cbQN2nmOVd/python2/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/var/cache/jenkins/tmp.cbQN2nmOVd/python2/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/cache/jenkins/tmp.cbQN2nmOVd/python2/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/var/cache/jenkins/tmp.cbQN2nmOVd/python2/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/var/cache/jenkins/tmp.cbQN2nmOVd/python2/local/lib/python2.7/site-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/var/cache/jenkins/tmp.cbQN2nmOVd/python2/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 168, in handle_noargs
    collected = self.collect()
  File "/var/cache/jenkins/tmp.cbQN2nmOVd/python2/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 114, in collect
    for original_path, processed_path, processed in processor:
  File "/var/cache/jenkins/tmp.cbQN2nmOVd/python2/local/lib/python2.7/site-packages/pipeline/storage.py", line 33, in post_process
    packager.pack_javascripts(package)
  File "/var/cache/jenkins/tmp.cbQN2nmOVd/python2/local/lib/python2.7/site-packages/pipeline/packager.py", line 112, in pack_javascripts
    return self.pack(package, self.compressor.compress_js, js_compressed, templates=package.templates, **kwargs)
  File "/var/cache/jenkins/tmp.cbQN2nmOVd/python2/local/lib/python2.7/site-packages/pipeline/packager.py", line 106, in pack
    content = compress(paths, **kwargs)
  File "/var/cache/jenkins/tmp.cbQN2nmOVd/python2/local/lib/python2.7/site-packages/pipeline/compressors/__init__.py", line 67, in compress_js
    js = getattr(compressor(verbose=self.verbose), 'compress_js')(js)
  File "/var/cache/jenkins/tmp.cbQN2nmOVd/python2/local/lib/python2.7/site-packages/pipeline/compressors/slimit.py", line 13, in compress_js
    return minify(js)
  File "/var/cache/jenkins/tmp.cbQN2nmOVd/python2/local/lib/python2.7/site-packages/slimit/minifier.py", line 37, in minify
    parser = Parser()
  File "/var/cache/jenkins/tmp.cbQN2nmOVd/python2/local/lib/python2.7/site-packages/slimit/parser.py", line 56, in __init__
    self.lexer.build(optimize=lex_optimize, lextab=lextab)
  File "/var/cache/jenkins/tmp.cbQN2nmOVd/python2/local/lib/python2.7/site-packages/slimit/lexer.py", line 102, in build
    self.lexer = ply.lex.lex(object=self, **kwargs)
  File "/var/cache/jenkins/tmp.cbQN2nmOVd/python2/local/lib/python2.7/site-packages/ply/lex.py", line 893, in lex
    if '.' not in lextab:
TypeError: argument of type 'module' is not iterable
```

**Comment by brianmay** [comment]
Apparently ply 3.6 fixes this; need to test.

**Comment by brianmay** [comment]
Also ply 3.4 in Jessie should be fine.

**Comment by brianmay** [comment]
Somewhere, somehow, this appears to be fixed now.
