### ISSUE TITLE
[django-audit-log] KeyError: Manager (Django 1.8)

### ISSUE THREAD

**Issue by brianmay** [Karaage-Cluster/karaage#266]
```
======================================================================
ERROR: setUpClass (karaage.tests.test_people.PersonTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/python/local/lib/python2.7/site-packages/django/test/testcases.py", line 952, in setUpClass
    'database': db_name,
  File "/tmp/python/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/tmp/python/local/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/tmp/python/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 60, in handle
    self.loaddata(fixture_labels)
  File "/tmp/python/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 90, in loaddata
    self.load_label(fixture_label)
  File "/tmp/python/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 147, in load_label
    obj.save(using=self.using)
  File "/tmp/python/local/lib/python2.7/site-packages/django/core/serializers/base.py", line 173, in save
    models.Model.save_base(self.object, using=using, raw=True)
  File "/tmp/python/local/lib/python2.7/site-packages/django/db/models/base.py", line 747, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/tmp/python/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/brian/tree/django/karaage/karaage/karaage/people/models.py", line 508, in _project_membership_changed
    projectmembership__project=project,
  File "/home/brian/tree/django/karaage/karaage/karaage/people/models.py", line 644, in sync_members
    *[tmp_person_id for tmp_person_id in add_member_ids])
  File "/tmp/python/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 973, in add
    self._add_items(self.source_field_name, self.target_field_name, *objs)
  File "/tmp/python/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1105, in _add_items
    model=self.model, pk_set=new_ids, using=db)
  File "/tmp/python/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/brian/tree/django/karaage/karaage/karaage/people/models.py", line 709, in _members_changed
    _add_person_to_group(person, group)
  File "/home/brian/tree/django/karaage/karaage/karaage/people/models.py", line 674, in _add_person_to_group
    add_accounts_to_project(a_list, group.project)
  File "/home/brian/tree/django/karaage/karaage/karaage/datastores/__init__.py", line 473, in add_accounts_to_project
    query = query.filter(machine_category__projectquota__project=project)
  File "/tmp/python/local/lib/python2.7/site-packages/django/db/models/query.py", line 679, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/tmp/python/local/lib/python2.7/site-packages/django/db/models/query.py", line 697, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/tmp/python/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1305, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "/tmp/python/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1332, in _add_q
    current_negated=current_negated, connector=connector, allow_joins=allow_joins)
  File "/tmp/python/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1150, in build_filter
    value, lookups, used_joins = self.prepare_lookup_value(value, lookups, can_reuse, allow_joins)
  File "/tmp/python/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 997, in prepare_lookup_value
    value = value()
  File "/tmp/python/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 691, in __call__
    manager = getattr(self.model, kwargs.pop('manager'))
KeyError: u"Problem installing fixture '/home/brian/tree/django/karaage/karaage/karaage/fixtures/test_karaage.json': u'manager'"

----------------------------------------------------------------------
```

See https://code.djangoproject.com/ticket/24768

**Comment by brianmay** [comment]
This doesn't happen with Karaage3, which seems surprising.

**Comment by brianmay** [comment]
Doesn't happen in Karaage3, because Karaage3 doesn't use django-audit-log.

See https://github.com/Atomidata/django-audit-log/issues/21

**Comment by brianmay** [comment]
No release of django-audit-log since before this ticket was opened in 2015. Probably should drop django-audit-log if we ever resume Karaage4. In any case, going to close this for now.
