### ISSUE TITLE
Approve after duplicate sent emails to deleted karaage admins

### ISSUE THREAD

**Issue by AndrewIsaac** [Karaage-Cluster/karaage#268]
In the user application process, a karaage admin clicked the 'is duplicate' (expecting it to take them to another page) then hit the back button and clicked approved.
This resulted in a server error.
BUT, only after sending the
'This application is now waiting for an administrator to process the application.'
e-mails to all Karaage admins *including* deleted admins.
Process failed when slurm command tried to add user to project (that we assume is not in LDAP)

Although I don't think this is related to slurm, here's stack trace of the slurm fail, hopefully it points to the right area.

**Comment by AndrewIsaac** [comment]
Internal Server Error: /karaage/applications/3055/K/approve/
Traceback (most recent call last):
 File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/usr/lib/python2.7/dist-packages/django/db/transaction.py", line 394, in inner
   return func(*args, **kwargs)
 File "/usr/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
   return view_func(request, *args, **kwargs)
 File "/usr/lib/python2.7/dist-packages/karaage/plugins/kgapplications/views/common.py", line 135, in application_detail
   return state_machine.process(request, application, state, label)
 File "/usr/lib/python2.7/dist-packages/karaage/plugins/kgapplications/views/base.py", line 211, in process
   return self._next(request, application, roles, next_state_key)
 File "/usr/lib/python2.7/dist-packages/karaage/plugins/kgapplications/views/base.py", line 238, in _next
   request, application, roles)
 File "/usr/lib/python2.7/dist-packages/karaage/plugins/kgapplications/views/states.py", line 192, in get_next_state
   created_person, created_account = application.approve(approved_by)
 File "/usr/lib/python2.7/dist-packages/karaage/plugins/kgapplications/models.py", line 320, in approve
   Account.create(person, self.project, pc.machine_category)
 File "/usr/lib/python2.7/dist-packages/karaage/machines/models.py", line 204, in create
   person.add_group(default_project.group)
 File "/usr/lib/python2.7/dist-packages/karaage/people/models.py", line 385, in add_group
   group.members.add(self)
 File "/usr/lib/python2.7/dist-packages/django/db/models/fields/related.py", line 924, in add
   self._add_items(self.source_field_name, self.target_field_name, *objs)
 File "/usr/lib/python2.7/dist-packages/django/db/models/fields/related.py", line 1050, in _add_items
   model=self.model, pk_set=new_ids, using=db)
 File "/usr/lib/python2.7/dist-packages/django/dispatch/dispatcher.py", line 198, in send
   response = receiver(signal=self, sender=sender, **named)
 File "/usr/lib/python2.7/dist-packages/karaage/people/models.py", line 529, in _members_changed
   _add_person_to_group(person, group)
 File "/usr/lib/python2.7/dist-packages/karaage/people/models.py", line 494, in _add_person_to_group
   add_accounts_to_project(a_list, project)
 File "/usr/lib/python2.7/dist-packages/karaage/datastores/__init__.py", line 475, in add_accounts_to_project
   machine_category_add_account_to_project(account, project)
 File "/usr/lib/python2.7/dist-packages/karaage/datastores/__init__.py", line 283, in machine_category_add_account_to_project
   datastore.add_account_to_project(account, project)
 File "/usr/lib/python2.7/dist-packages/karaage/common/trace.py", line 533, in wrapper
   result = _func(*__argv, **__kwds)
 File "/usr/lib/python2.7/dist-packages/karaage/datastores/slurm.py", line 340, in add_account_to_project
   "name=%s" % username])
 File "/usr/lib/python2.7/dist-packages/karaage/common/trace.py", line 533, in wrapper
   result = _func(*__argv, **__kwds)
 File "/usr/lib/python2.7/dist-packages/karaage/datastores/slurm.py", line 127, in _call
   raise subprocess.CalledProcessError(retcode, command)
CalledProcessError: Command '['sudo', '-uslurm', '/usr/local/slurm/latest/bin/sacctmgr', '-ip', 'add', 'user', u'accounts=VR0138', u'name=mayere']' returned non-zero exit status 1

**Comment by brianmay** [comment]
Was the user already in the project? Suspect this is a similar case to before, the slurm command failed because there was nothing to do, the user was already in the project. If so, I can fix this.

**Comment by AndrewIsaac** [comment]
> On 15 May 2015, at 1:24 pm, Brian May <notifications@github.com> wrote:
> 
> Was the user already in the project? Suspect this is a similar case to before, the slurm command failed because there was nothing to do, the user was already in the project. If so, I can fix this.

slurm command failing is not the problem (just a symptom)

the problems are:
- hitting 'is duplicate' deleted the application, but then clicking browser back button and application approve appears to have tried to approve a deleted application and recreated the 'application is waiting for administration approval' emails, and
- that the e-mails were (also) sent to deleted karaage admins -- that then spammed us with bounced e-mails

**Comment by brianmay** [comment]
The second part sounds like #267?

**Comment by brianmay** [comment]
Just trying to make sure I understand you here. What you are saying is:

1. Application is waiting for system administrator approval.
2. System administrator goes to the approve page, but doesn't click the final approve button.
3. System administrator clicks the "is existing user button".
4. System administrator clicks the back button. Which redisplays the approve page from step 2.
5. System administrator clicks the approve button.
6. This generates an email 'application is waiting for administration approval', and attempts to approve the application.
7. Approving the application itself fails, because the user is already in the project.

This doesn't make a lot of sense (I am looking at the code now which should stop any actions in "Waiting for admin approval state" from working if the application is not in "waiting for admin approval state"), however I want to make sure I understand the exact sequence before trying to reproduce this myself.

**Comment by brianmay** [comment]
Also the standard used is that buttons carry out an action immediately without any confirmation, and the links are read only and will not make any changes. Think this confuses people however, wonder if it is possible to clarify some how.

**Comment by brianmay** [comment]
Are you sure you (or somebody else) hasn't clicked the "reopen" button for the application at some point after clicking "is existing user"?

**Comment by brianmay** [comment]
Also: The logs associated with the application could be useful to find out what went wrong.
