### ISSUE TITLE
TypeError: 'InstituteDelegateFormFormSet' object is not callable

### ISSUE THREAD

**Issue by AndrewIsaac** [Karaage-Cluster/karaage#271]
Adding an Institute gave; TypeError: 'InstituteDelegateFormFormSet' object is not callable

/var/log/karaage3/django.log
...
ERROR 2015-05-25 16:04:39,631 base 5709 140412679993088 Internal Server Error: /karaage/institutes/add/
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/dist-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/karaage/institutes/views.py", line 158, in add_edit_institute
    request.POST, instance=institute)
TypeError: 'InstituteDelegateFormFormSet' object is not callable

**Comment by brianmay** [comment]
I guess you were trying to add an institute when this happened?

**Comment by brianmay** [comment]
I see the problem, we seem to use the ``delegate_formset`` variable for two different purposes, and as a result we don't have the expected value when we need it.

**Comment by brianmay** [comment]
This was a bug introduced by ee39b0801f49517bce7a68c7f70c60ed7a2bb537.
