### ISSUE TITLE
Deleting Person before deleting Account causes ds389_account_group matching query does not exist

### ISSUE THREAD

**Issue by AndrewIsaac** [Karaage-Cluster/karaage#277]
Tried to delete a user and got server error.
Deleting user's account first, then deleting user worked

```
trace:
Internal Server Error: /karaage/persons/detail/achaves/delete/
Traceback (most recent call last):
 File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/usr/lib/python2.7/dist-packages/django/db/transaction.py", line 394, in inner
   return func(*args, **kwargs)
 File "/usr/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
   return view_func(request, *args, **kwargs)
 File "/usr/lib/python2.7/dist-packages/karaage/people/views/persons.py", line 150, in delete_user
   person.deactivate(deleted_by)
 File "/usr/lib/python2.7/dist-packages/karaage/people/models.py", line 351, in deactivate
   self.groups.clear()
 File "/usr/lib/python2.7/dist-packages/django/db/models/fields/related.py", line 946, in clear
   model=self.model, pk_set=None, using=db)
 File "/usr/lib/python2.7/dist-packages/django/dispatch/dispatcher.py", line 198, in send
   response = receiver(signal=self, sender=sender, **named)
 File "/usr/lib/python2.7/dist-packages/karaage/machines/models.py", line 486, in _members_changed
   _remove_group(group, person)
 File "/usr/lib/python2.7/dist-packages/karaage/machines/models.py", line 456, in _remove_group
   ua.save()
 File "/usr/lib/python2.7/dist-packages/model_utils/tracker.py", line 134, in save
   ret = original_save(**kwargs)
 File "/usr/lib/python2.7/dist-packages/karaage/machines/models.py", line 323, in save
   machine_category_save_account(self)
 File "/usr/lib/python2.7/dist-packages/karaage/datastores/__init__.py", line 241, in machine_category_save_account
   datastore.save_account(account)
 File "/usr/lib/python2.7/dist-packages/karaage/common/trace.py", line 533, in wrapper
   result = _func(*__argv, **__kwds)
 File "/usr/lib/python2.7/dist-packages/karaage/datastores/ldap.py", line 256, in save_account
   lgroup = self._groups().get(cn=self._default_primary_group)
 File "/usr/lib/python2.7/dist-packages/tldap/query.py", line 506, in get
   self._cls._meta.object_name)
tldap.exceptions.DoesNotExist: ds389_account_group matching query does not exist.
```

**Comment by brianmay** [comment]
Looks a bit like Karaage thought that person was in a group, but LDAP thought otherwise...

**Comment by brianmay** [comment]
Sorry, disregard my previous commit.

The error happens because we set the primary group to be the the primary project.

However there is no primary project. So it reverts to the DEFAULT_PRIMARY_GROUP value or dummy if this does not exist.

It appears your DEFAULT_PRIMARY_GROUP value (or dummy) does not exist as a group in your LDAP database. Hence you probably should fix this...

Does this make sense?

**Comment by brianmay** [comment]
On second thoughts, we probably should deactivate the accounts first, then remove the groups. This should avoid this problem. However, it is possible a person might not have a primary project, so the DEFAULT_PRIMARY_GROUP should still exist.
