### ISSUE TITLE
Adding new Institutes causes 500 & stacktrace

### ISSUE THREAD

**Issue by DanielTosello** [Karaage-Cluster/karaage#284]
Attempting to add a new institute *with a delegate* via the admin institutes GUI causes a 500 in browser and stacktrace in django.log:
```
ERROR 2016-08-29 10:33:12,139 base 31862 140135060440832 Internal Server Error: /karaage/institutes/add/
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/dist-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/karaage/institutes/views.py", line 159, in add_edit_institute
    delegate_formset.save()
  File "/usr/lib/python2.7/dist-packages/django/forms/models.py", line 636, in save
    return self.save_existing_objects(commit) + self.save_new_objects(commit)
  File "/usr/lib/python2.7/dist-packages/django/forms/models.py", line 767, in save_new_objects
    self.new_objects.append(self.save_new(form, commit=commit))
  File "/usr/lib/python2.7/dist-packages/django/forms/models.py", line 900, in save_new
    obj.save()
  File "/usr/lib/python2.7/dist-packages/model_utils/tracker.py", line 134, in save
    ret = original_save(**kwargs)
  File "/usr/lib/python2.7/dist-packages/karaage/institutes/models.py", line 217, in save
    super(InstituteDelegate, self).save(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 685, in save
    "unsaved related object '%s'." % field.name
ValueError: save() prohibited to prevent data loss due to unsaved related object 'institute'.
```

Adding a new institute without a delegate returns a form error as expected, but creates the institute record anyway. I am currently using this as a workaround & adding delegates after institute creation. I assume this means that there is a model relationship issue.

Note i manually created the group entry after finding this error but before finding the workaround. The institute correctly associated with the group i created for it. It is possible that the model issue is also affected by the existence of the associated group but providing it manually isn't a sufficient fix.

**Comment by brianmay** [comment]
I reverted that change, it was broken.
