### ISSUE TITLE
latest slap breaks tests

### ISSUE THREAD

**Issue by brianmay** [Karaage-Cluster/karaage#289]
```
======================================================================
ERROR: test_delete_project (karaage.tests.projects.test_projects.ProjectTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brian/tree/karaage/karaage/karaage/tests/projects/test_projects.py", line 33, in setUp
    super(ProjectTestCase, self).setUp()
  File "/home/brian/tree/karaage/karaage/karaage/tests/integration.py", line 70, in setUp
    server.start()
  File "/home/brian/tree/karaage/karaage/.tox/py35-django19/lib/python3.5/site-packages/tldap/test/slapd.py", line 203, in start
    self._test_configuration()
  File "/home/brian/tree/karaage/karaage/.tox/py35-django19/lib/python3.5/site-packages/tldap/test/slapd.py", line 305, in _test_configuration
    raise RuntimeError("configuration test failed")
RuntimeError: configuration test failed
```

**Comment by brianmay** [comment]
This was fixed in https://github.com/Karaage-Cluster/python-tldap/commit/256cc49f0a14a33b9ce91357ad5ea5892a0ebbf5
