### ISSUE TITLE
Prevent passwords being sent in plain text stack trace

### ISSUE THREAD

**Issue by AndrewIsaac** [Karaage-Cluster/karaage#292]
When there is a server error during login, plain text e-mail is sent with request info.  This info includes the password.
Ideally need to catch any field labeled (or containing) password and remove plain text string.

Example follows:
Internal Server Error: /karaage/profile/login/
Traceback (most recent call last):
 File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/usr/lib/python2.7/dist-packages/django/db/transaction.py", line 394, in inner
   return func(*args, **kwargs)
 File "/usr/lib/python2.7/dist-packages/karaage/people/views/profile.py", line 50, in login
   username=username, password=password)
 File "/usr/lib/python2.7/dist-packages/karaage/people/managers.py", line 25, in authenticate
   return authenticate(username=username, password=password)
 File "/usr/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 60, in authenticate
   user = backend.authenticate(**credentials)
 File "/usr/lib/python2.7/dist-packages/karaage/backends.py", line 40, in authenticate
   person.save()
 File "/usr/lib/python2.7/dist-packages/model_utils/tracker.py", line 134, in save
   ret = original_save(**kwargs)
 File "/usr/lib/python2.7/dist-packages/karaage/people/models.py", line 152, in save
   machine_category_save_account(ua)
 File "/usr/lib/python2.7/dist-packages/karaage/datastores/__init__.py", line 241, in machine_category_save_account
   datastore.save_account(account)
 File "/usr/lib/python2.7/dist-packages/karaage/common/trace.py", line 533, in wrapper
   result = _func(*__argv, **__kwds)
 File "/usr/lib/python2.7/dist-packages/karaage/datastores/slurm.py", line 313, in save_account
   self._save_account(account, account.username)
 File "/usr/lib/python2.7/dist-packages/karaage/common/trace.py", line 533, in wrapper
   result = _func(*__argv, **__kwds)
 File "/usr/lib/python2.7/dist-packages/karaage/datastores/slurm.py", line 296, in _save_account
   for project in account.person.projects.all():
 File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 141, in __iter__
   self._fetch_all()
 File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 966, in _fetch_all
   self._result_cache = list(self.iterator())
 File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 265, in iterator
   for row in compiler.results_iter():
 File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 700, in results_iter
   for rows in self.execute_sql(MULTI):
 File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
   cursor.execute(sql, params)
 File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
   return self.cursor.execute(sql, params)
 File "/usr/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
   six.reraise(dj_exc_type, dj_exc_value, traceback)
 File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
   return self.cursor.execute(sql, params)
 File "/usr/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 129, in execute
   return self.cursor.execute(query, args)
 File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
   self.errorhandler(self, exc, value)
 File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
   raise errorclass, errorvalue
OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')

Request repr(): 
<WSGIRequest
path:/karaage/profile/login/,
GET:<QueryDict: {u'next': [u'/karaage/profile/accounts/']}>,
POST:<QueryDict: {u'username': [u'USER1'], u'csrfmiddlewaretoken': [u'DELETED'], u'password': [u'USERSPASSWORD'], u'this_is_the_login_form': [u'1'], u'next': [u'/karaage/profile/accounts/']}>,
COOKIES:{'_ga': 'DELETED',
'csrftoken': 'DELETED'},
META:{'CONTENT_LENGTH': '156',
'CONTENT_TYPE': 'application/x-www-form-urlencoded',
u'CSRF_COOKIE': u'DELETED',
'DOCUMENT_ROOT': '/var/www',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTPS': '1',
'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
'HTTP_ACCEPT_LANGUAGE': 'en-GB,en-US;q=0.8,en;q=0.6',
'HTTP_CACHE_CONTROL': 'max-age=0',
'HTTP_CONNECTION': 'keep-alive',
'HTTP_COOKIE': '_ga=DELETED; csrftoken=DELETED',
'HTTP_HOST': 'my.example.com',
'HTTP_ORIGIN': 'https://my.example.com',
'HTTP_REFERER': 'https://my.example.com/karaage/profile/login/?next=/karaage/profile/accounts/',
'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36',
'PATH_INFO': u'/profile/login/',
'PATH_TRANSLATED': '/var/www/profile/login/',
'QUERY_STRING': 'next=/karaage/profile/accounts/',
'REMOTE_ADDR': 'DELETED',
'REMOTE_PORT': 'DELETED',
'REQUEST_METHOD': 'POST',
'REQUEST_URI': '/karaage/profile/login/?next=/karaage/profile/accounts/',
'SCRIPT_FILENAME': '/etc/karaage3/karaage.wsgi',
'SCRIPT_NAME': u'/karaage',
'SCRIPT_URI': 'https://my.example.com/karaage/profile/login/',
'SCRIPT_URL': '/karaage/profile/login/',
'SERVER_ADDR': 'DELETED',
'SERVER_ADMIN': 'webmaster@example.com',
'SERVER_NAME': 'my.example.com',
'SERVER_PORT': '443',
'SERVER_PROTOCOL': 'HTTP/1.1',
'SERVER_SIGNATURE': '<address>Apache/2.2.22 (Debian) Server at my.example.com Port 443</address>\n',
'SERVER_SOFTWARE': 'Apache/2.2.22 (Debian)',
'SSL_TLS_SNI': 'my.example.com',
'mod_wsgi.application_group': 'my.example.com|/karaage',
'mod_wsgi.callable_object': 'application',
'mod_wsgi.handler_script': '',
'mod_wsgi.input_chunked': '0',
'mod_wsgi.listener_host': '',
'mod_wsgi.listener_port': '443',
'mod_wsgi.process_group': '',
'mod_wsgi.request_handler': 'wsgi-script',
'mod_wsgi.script_reloading': '1',
'mod_wsgi.version': (3, 3),
'wsgi.errors': <mod_wsgi.Log object at 0x7f97091c4470>,
'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f97091c8828>,
'wsgi.input': <mod_wsgi.Input object at 0x7f97091ba130>,
'wsgi.multiprocess': True,
'wsgi.multithread': False,
'wsgi.run_once': False,
'wsgi.url_scheme': 'https',
'wsgi.version': (1, 1)}>

**Comment by brianmay** [comment]
Deadlock? That doesn't sound healthy.

The relevant [Django documentation](https://docs.djangoproject.com/en/1.10/howto/error-reporting/#filtering-sensitive-information) - want to create a pull request?

**Comment by brianmay** [comment]
Fixed in https://github.com/Karaage-Cluster/karaage/commit/6e9c99265c55ac21f17759cb1cfe917494164deb

It is possible I may have missed views that require a password. If so, please let me know so I can fix them.
